.TH SNES9X-GTK 1 "01 JAN 2010" "Debian Project" "Debian Linux"
.SH NAME
snes9x-gtk \- A GTK port of the Snes9x Super Nintendo emulator
.SH DESCRIPTION
Snes9x is a portable, freeware Super Nintendo Entertainment System (SNES)
emulator. It basically allows you to play most games designed for the SNES
and Super Famicom Nintendo game systems on your PC or Workstation; they
include some real gems that were only ever released in Japan.
Snes9x-gtk is a graphical frontend for Snes9x which can be run on UNIX-like OSes.
.SS OPTIONS
.B snes9x-gtk
.TP
.I \-filter [option]
Use a filter to scale the image. [option] is one of: none, supereagle,
2xsai, super2xsai, hq2x, hq3x, hq4x, epx, ntsc (Default is none)
.TP
.I \-mutesound
Disables sound output.
.SH SEE ALSO
.BR snes9express (1),
.BR snes9x-x (1),
.BR zsnes (1)
.\".BR s9xserver (1)
.SH AUTHOR
Snes9x-gtk was written by Brandon Wright <bearoso@gmail.com>.
This manual page was written by Kostic Milan <smoki00790@gmail.com>,
for the Debian GNU/Linux system (but may be used by others).

